# I made this as a stub file to allow the DAG to parse and appear in the Airflow UI, even though the actual implementation of each stage is not yet complete. Each function raises NotImplementedError with a message indicating that the work is pending. I'll be honest the entire text was auto generated by VS Code I just clicked Tab to accept it lol.
def validate_raw_batch(source_id: str, batch_id: str, raw_root: str) -> dict:
    """
    Validate a single raw-layer batch produced by an extractor.

    Returns a dict with at least:
        {"batch_id": str, "source_id": str, "rows": int, "passed": bool,
         "details": str}

    Raises on unrecoverable failure (e.g. manifest missing). """
    raise NotImplementedError(
        "raw_validate stage not yet implemented. Member B's workstream "
        "provides this. Until then, DAG runs will fail here by design - "
        "the DAG itself parses and appears in the Airflow UI."
    )

def stage_source(source_id: str, batch_id: str, raw_root: str,
                 staging_root: str, config_path: str) -> dict:
    """
    Execute config/adapters/<source_id>.yaml's field_mapping against the
    raw batch to produce a staging-layer output.

    Returns a dict with at least:
        {"batch_id": str, "source_id": str, "rows_in": int,
         "rows_out": int, "staging_path": str, "passed": bool}

    Idempotent on rerun for the same (source_id, batch_id). """
    raise NotImplementedError(
        "stage stage not yet implemented. Member B's workstream provides "
        "this."
    )

def validate_staged(source_id: str, batch_id: str, staging_root: str,
                    checks: list[str], dq_run_log_conn: dict) -> dict:
    """
    Run the configured data-quality checks against a staged batch, writing
    one row per check to dq_run_log.

    `checks` is the list of check names to run, e.g.
        ["schema", "nullability", "uniqueness", "accepted_values",
         "range", "row_count_reconciliation"]

    Returns a dict with at least:
        {"batch_id": str, "source_id": str,
         "checks_run": int, "checks_failed": int,
         "quarantined_rows": int, "passed": bool}
    """
    raise NotImplementedError(
        "validate stage not yet implemented. Member B's workstream "
        "provides this."
    )

def harmonize_to_canonical(source_id: str, batch_id: str,
                           staging_root: str, curated_root: str,
                           canonical_schema_path: str,
                           config_path: str) -> dict:
    """
    Transform this source's staged data into the canonical schema, writing
    curated Parquet partitioned by source_id/year/month (per proposal
    section 9).

    Returns a dict with at least:
        {"batch_id": str, "source_id": str, "rows": int,
         "curated_path": str, "passed": bool}

    Replace-partition semantics on rerun: re-running for the same
    (source_id, year, month) replaces that partition, does not append.
    """
    raise NotImplementedError(
        "harmonize stage not yet implemented. Member B's workstream "
        "provides this."
    )

def load_postgres(source_id: str, batch_id: str, curated_root: str,
                  db_conn: dict) -> dict:
    """
    Load this source's curated output into the PostgreSQL curated layer
    defined by sql/schema.sql, UPSERTing on the natural key
    (source_id, source_record_id) for rerun safety.

    Also ensures dim_date has rows for every crash_date_key in this batch.

    Returns a dict with at least:
        {"batch_id": str, "source_id": str, "rows_upserted": int,
         "rows_inserted": int, "rows_updated": int, "passed": bool}

    `db_conn` is a dict: {"host": str, "port": int, "dbname": str,
    "user": str, "password": str}. The DAG reads these from environment
    variables populated by docker-compose.yml (PIPELINE_POSTGRES_*).
    """
    raise NotImplementedError(
        "load_postgres stage not yet implemented. Member B's workstream "
        "provides this."
    )

def publish_parquet(source_id: str, batch_id: str, curated_root: str,
                    publish_root: str) -> dict:
    """
    Publish this source's curated output as partitioned Parquet under
    source_id/year/month. Confirm the partition is readable without a
    full scan (this is what the live demonstration exercises).

    Returns a dict with at least:
        {"batch_id": str, "source_id": str, "partitions_written": int,
         "published_path": str, "passed": bool}
    """
    raise NotImplementedError(
        "publish_parquet stage not yet implemented. Member B's workstream "
        "provides this."
    )

def build_quality_report(source_id: str, batch_id: str,
                         dq_run_log_conn: dict, report_root: str) -> dict:
    """
    Produce a quality-report artifact for this batch, summarizing the
    dq_run_log rows written by the validate stage.

    Returns a dict with at least:
        {"batch_id": str, "source_id": str, "report_path": str,
         "checks_passed": int, "checks_failed": int, "passed": bool}

    This stage is read-only: it never modifies fact_crash or dq_run_log.
    """
    raise NotImplementedError(
        "quality_report stage not yet implemented. Member B's workstream "
        "provides this."
    )

def cleanup_failed_batch(source_id: str, batch_id: str,
                         raw_root: str, staging_root: str,
                         curated_root: str, dry_run: bool = True) -> dict:
    """
    Called by the DAG's on_failure_callback. In dry_run mode (default),
    reports what WOULD be cleaned; in non-dry-run mode, removes
    intermediate artifacts for this batch. Never touches the raw layer:
    raw is source-faithful and always retained for lineage.

    Returns a dict with at least:
        {"batch_id": str, "source_id": str, "would_remove": [str],
         "removed": [str], "dry_run": bool}
    """
    raise NotImplementedError(
        "cleanup_failed_batch not yet implemented. Optional - the DAG "
        "works without it; add it once Member B's modules exist and the "
        "failure semantics are settled."
    )